db:
  socket: "/var/run/mysqld/mysqld.sock"
  name: "{{ db_name }}"
  user: "{{ db_user }}"
  passwd: "{{ db_passwd }}"
  host: "{{ db_host }}"

wp_ver: "5.8"
wp:
  url: "https://wordpress.org/wordpress-{{ wp_ver }}.tar.gz"
  sha1: "sha1:6476e69305ba557694424b04b9dea7352d988110"
  source: "/home/ubuntu/wordpress-{{ wp_ver }}.tar.gz"
  config: "/var/www/html/wordpress/wp-config.php"

port_var:
  service_port: "{{ service_port }}"

